# Generated by Django 4.0 on 2022-06-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='best',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='best',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
